import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/components/auth-provider";
import React, { ReactNode } from "react";
import { AppThemeProvider } from "@/components/theme-provider";
import { auth } from "@/libs/auth";
import SwitchMode from "@/components/switch-mode";
import Settings from "@/components/settings";
import UserMenu from "@/components/user-menu";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const authn = await auth();
  const user = authn?.user;

  return (
    <html lang="en" suppressHydrationWarning>
      <AuthProvider>
        <body className={inter.className}>
          <AppThemeProvider>
            <main className="flex min-h-screen">
              <div className="flex-1">
                <Header>
                  <SwitchMode />
                  {/* <Settings /> */}
                  <UserMenu
                    user={{
                      name: user?.name,
                      image: user?.image,
                      email: user?.email,
                    }}
                  />
                </Header>
                <Sidebar className="fixed hidden border-r xl:flex overflow-y-auto h-screen" />

                <div className="container mt-24 pb-8 xl:pl-[256px]">
                  {children}
                </div>
              </div>
            </main>
          </AppThemeProvider>
        </body>
      </AuthProvider>
    </html>
  );
}
